### ISSUE TITLE
HA error with version 1.13.0

### ISSUE THREAD

**Issue by derjoerg** [kingsleyadam/local-abbfreeathome#105]
When I try to use version 1.13.0 in the current HA-integration I get the following error:
```
2024-11-09 10:11:32.071 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None):   File "/home/vscode/.local/ha-venv/bin/hass", line 8, in <module>
    sys.exit(main())
  File "/workspaces/homeassistant_core/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/workspaces/homeassistant_core/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1978, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/workspaces/homeassistant_core/homeassistant/config_entries.py", line 774, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/workspaces/homeassistant_core/homeassistant/config_entries.py", line 537, in async_setup
    await self.__async_setup_with_context(hass, integration)
  File "/workspaces/homeassistant_core/homeassistant/config_entries.py", line 626, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
  File "/workspaces/homeassistant_core/config/custom_components/abbfreeathome_ci/__init__.py", line 86, in async_setup_entry
    entry.async_create_background_task(hass, _free_at_home.ws_listen(), f"{DOMAIN}_ws")
  File "/workspaces/homeassistant_core/homeassistant/config_entries.py", line 1166, in async_create_background_task
    task = hass.async_create_background_task(target, name, eager_start)
  File "/workspaces/homeassistant_core/homeassistant/core.py", line 864, in async_create_background_task
    task = create_eager_task(target, name=name, loop=self.loop)
  File "/workspaces/homeassistant_core/homeassistant/util/async_.py", line 45, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
Traceback (most recent call last):
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/abbfreeathome/freeathome.py", line 174, in ws_listen
    await self.api.ws_listen(callback=self.update_device)
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/abbfreeathome/api.py", line 261, in ws_listen
    await self.ws_receive(callback, retry_interval)
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/abbfreeathome/api.py", line 287, in ws_receive
    await callback(_ws_data)
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/abbfreeathome/freeathome.py", line 182, in update_device
    _device.update_device(_datapoint_key, _datapoint_value)
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/abbfreeathome/devices/base.py", line 112, in update_device
    if _refreshed and self._callbacks:
       ^^^^^^^^^^
UnboundLocalError: cannot access local variable '_refreshed' where it is not associated with a value
```

It seems to be related to my changes in #103

**Comment by derjoerg** [comment]
And here, if I run a program only with the lib:
```
INFO:local_abbfreeathome.src.abbfreeathome.devices.base:Bewegungsmelder Flur zu Büro  received updated data: ABB700DA100B/ch0000/idp0000: 1
Traceback (most recent call last):
  File "c:\Users\joerg\programming\new_freeathome\test.py", line 79, in <module>
    asyncio.run(_free_at_home.ws_listen())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\joerg\programming\new_freeathome\local_abbfreeathome\src\abbfreeathome\freeathome.py", line 174, in ws_listen
    await self.api.ws_listen(callback=self.update_device)
  File "c:\Users\joerg\programming\new_freeathome\local_abbfreeathome\src\abbfreeathome\api.py", line 261, in ws_listen
    await self.ws_receive(callback, retry_interval)
  File "c:\Users\joerg\programming\new_freeathome\local_abbfreeathome\src\abbfreeathome\api.py", line 287, in ws_receive
    await callback(_ws_data)
  File "c:\Users\joerg\programming\new_freeathome\local_abbfreeathome\src\abbfreeathome\freeathome.py", line 182, in update_device
    _device.update_device(_datapoint_key, _datapoint_value)
  File "c:\Users\joerg\programming\new_freeathome\local_abbfreeathome\src\abbfreeathome\devices\base.py", line 112, in update_device
    if _refreshed and self._callbacks:
       ^^^^^^^^^^
UnboundLocalError: cannot access local variable '_refreshed' where it is not associated with a value
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001B1DF151F70>
Exception ignored in: <function ClientResponse.__del__ at 0x000001B1DECD4E00>
Traceback (most recent call last):
  File "C:\Users\joerg\programming\new_freeathome\.venv\Lib\site-packages\aiohttp\client_reqrep.py", line 973, in __del__
  File "C:\Users\joerg\programming\new_freeathome\.venv\Lib\site-packages\aiohttp\connector.py", line 191, in release
  File "C:\Users\joerg\programming\new_freeathome\.venv\Lib\site-packages\aiohttp\connector.py", line 686, in _release
  File "C:\Users\joerg\programming\new_freeathome\.venv\Lib\site-packages\aiohttp\client_proto.py", line 69, in close
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\proactor_events.py", line 109, in close
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 795, in call_soon
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 541, in _check_closed
RuntimeError: Event loop is closed
```
The problem is, I think, that it can happen, that - for whatever reason - an "input-datapoint" is sent on the websocket.
