### ISSUE TITLE
Websocket example not working anymore

### ISSUE THREAD

**Issue by derjoerg** [kingsleyadam/local-abbfreeathome#133]
When I try to run the websocket-example I get the following error-message:
```
DEBUG:asyncio:Using proactor: IocpProactor
Garagentor ABB28EBC3651 ch0012
DEBUG:asyncio:Using proactor: IocpProactor
INFO:local_abbfreeathome.src.abbfreeathome.api:Websocket attempting to connect ws://192.168.200.30/fhapi/v1/api/ws
Traceback (most recent call last):
  File "c:\Users\joerg\programming\new_freeathome\test.py", line 92, in <module>
    asyncio.run(_free_at_home.ws_listen())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\joerg\programming\new_freeathome\local_abbfreeathome\src\abbfreeathome\freeathome.py", line 174, in ws_listen
    await self.api.ws_listen(callback=self.update_device)
  File "c:\Users\joerg\programming\new_freeathome\local_abbfreeathome\src\abbfreeathome\api.py", line 302, in ws_listen
    await self.ws_receive(callback, retry_interval)
  File "c:\Users\joerg\programming\new_freeathome\local_abbfreeathome\src\abbfreeathome\api.py", line 310, in ws_receive
    await self.ws_connect()
  File "c:\Users\joerg\programming\new_freeathome\local_abbfreeathome\src\abbfreeathome\api.py", line 285, in ws_connect
    self._ws_response = await self._get_client_session().ws_connect(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joerg\programming\new_freeathome\.venv\Lib\site-packages\aiohttp\client.py", line 937, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joerg\programming\new_freeathome\.venv\Lib\site-packages\aiohttp\client.py", line 551, in _request
    handle = tm.start()
             ^^^^^^^^^^
  File "C:\Users\joerg\programming\new_freeathome\.venv\Lib\site-packages\aiohttp\helpers.py", line 649, in start
    return self._loop.call_at(when, self.__call__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 774, in call_at
    self._check_closed()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 541, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002875D5BBF20>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000002875DC660F0>, 544657.921)]']
connector: <aiohttp.connector.TCPConnector object at 0x000002875D8DB560>
```

Does it need some modifications regarding the ClientSession changes?

**Comment by derjoerg** [comment]
What I found out so far:

In `api.py` the method `_get_client_session()` is called within `asyncio.run(_free_at_home.load_devices())` and as `_client_session` is none a new `ClientSession()` is created.
The next time `_get_client_session()` is called within `asyncio.run(_free_at_home.ws_listen())` and as `_client_session` is already defined the current reference is returned. But this `ClientSession` object then produces the error.

**Comment by kingsleyadam** [comment]
There are two ways to fix this, you could create your own `ClientSession` object and pass it into the FreeAtHomeApi. That'll ensure the client session doesn't get caught without closure.

The other way is to ensure context management is used on the FreeAtHome api, that'll ensure the session is handled properly.

I've created a PR with this method.

```python
from abbfreeathome.api import FreeAtHomeApi
from abbfreeathome.freeathome import FreeAtHome
from abbfreeathome.devices.switch_actuator import SwitchActuator
import logging
import asyncio


async def websocket_test():
    # Create an instance of the api using context management
    async with FreeAtHomeApi(
        host="http://<IP or HOSTNAME>", username="installer", password="<password>"
    ) as _free_at_home_api:
        # Create an Instance of the FreeAtHome class
        _free_at_home = FreeAtHome(_free_at_home_api)

        # Load all devices into the FreeAtHome Class
        await _free_at_home.load_devices()

        # Add our very own callback
        for _switch in _free_at_home.get_devices_by_class(device_class=SwitchActuator):
            _switch.register_callback(my_very_own_callback)

        # Start listening for events.
        await _free_at_home.ws_listen()


def my_very_own_callback():
    print("The switches datapoints have been updated.")


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    asyncio.run(websocket_test())
```
